reason: final updates

diff --git a/main b/main
--- a/main
+++ b/main
@@ -4,18 +4,16 @@
 
 mkdir -p classification
 
-if [ ! -f eccentricity.nii.gz ]; then
-    [ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
-    echo $FREESURFER_LICENSE > license.txt
-    echo "converting appropriate parcellations"
-    time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer_on_mcr:6.0.2 ./convert.sh
+time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/eccentricityClassification
+
+if [ -f output.mat ]; then
+	echo "complete"
+	mkdir -p classification
+	mv output.mat ./classification/classification.mat
+	mv tracts ./classification/
+	mv output_fibercounts.txt ./classification/
+	exit 0
+else
+	echo "failed"
+	exit 1
 fi
-
-echo "creating hemispheric eccentricity rois"
-time singularity exec -e docker://brainlife/fsl:latest ./mask.sh
-
-#time singularity exec -e docker://brainlife/mcr:neurodebian1604-r2017a ./compiled/eccentricityClassification
-
-#mv output.mat ./classification/
-#mv tracts ./classification/
-#mv output_fibercounts.txt ./classification/
